config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|ja/ do
    get 'static_pages/home'
    get 'static_pages/help'
    get 'static_pages/contact'
    root 'static_pages#home'
    # resource :static_pages do
    #   collection do
    #     get :index
    #     get :help
    #     get :home
    #   end
    # end
    resources :microposts, only: [:create, :destroy, :index] do
      resources :comments
      resources :likes
    end
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/delete/:id", to: "users#destroy"
    resources :users do
      member do
        get :following, :followers
      end
      collection { post :import }
      collection { get :export }
    end
    resources :relationships, only: [:create, :destroy]
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    get "/logout", to: "sessions#destroy"
    resources :account_activations, only: :edit
    resources :password_resets, only: [:new, :create, :edit, :update] 
    namespace :api, defaults: { format: :json } do
      namespace :v1 do
        post "/login", to: "sessions#create"
        post "/comment", to: "microposts#comment"
        resources :users
        resources :microposts, only: [:index]
      end
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @micropost = current_user.microposts.build
    # @feed_items = current_user.feed.paginate(page: params[:page]).newest
    @feed_items = MicropostSearch.new(params[:search], params[:page]).execute!
  end

  def help; end

  def contact; end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/contact.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% provide :title, "Contact" %>
  </head>
  <body>
    <h1>Contact</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://www.railstutorial.org/help">Rails Tutorialhelp page</a>.
      To get help on this sample app, see the
      <a href="http://www.railstutorial.org/book"><em>Ruby on RailsTutorial</em>
      book</a>.
    </p>
  </body>
</html>

app/views/static_pages/help.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% provide :title, "Help" %>
  </head>
  <body>
    <h1>Help</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://www.railstutorial.org/help">Rails Tutorialhelp page</a>.
      To get help on this sample app, see the
      <a href="http://www.railstutorial.org/book"><em>Ruby on RailsTutorial</em>
      book</a>.
    </p>
  </body>
</html>

app/views/static_pages/home.html.erb
<%= javascript_include_tag 'micropost/micropost.js' %>
<%= javascript_include_tag 'handlebars' %>
<% if logged_in? %>
  <div class="row" style="
    display: flex;
    justify-content: center;">
    <div class="col-md-8">
      <div class="main-wraper">
        <ul class = "chat-rooms owl-carousel owl-theme owl-responsive-1000 owl-loaded">
          <div class="owl-stage-outer">
            <div class="owl-stage" style="transform: translate3d(0px, 0px, 0px); transition: all 0s ease 0s; width: 705px;">
              <div class="owl-item active" style="width: 126px; margin-right: 15px;">
                <li>
                  <div class="room-avatar">
                    <img class = "img-user"src="https://hddesktopwallpapers.in/wp-content/uploads/2015/09/resting-images.jpg" alt="Italian Trulli">
                  </div>
                  <span>Meo Meo</span>
                  <a class="join" href="#" title="Join Room">Add</a>
                </li>
              </div>
              <div class="owl-item active" style="width: 126px; margin-right: 15px;">
                <li>
                  <div class="room-avatar">
                    <img class = "img-user"src="https://hddesktopwallpapers.in/wp-content/uploads/2015/09/resting-images.jpg" alt="Italian Trulli">
                  </div>
                  <span>Meo Meo</span>
                  <a class="join" href="#" title="Join Room">Add</a>
                </li>
              </div>
            </div>
          </div>
        </ul>
      </div>
      <div style="margin-top: 180px;"></div>
      <%= link_to "Import User", import_users_path %>
      <%= link_to "Export Users", export_users_path(format: :csv) %>      
      <%= form_with url: static_pages_home_path, method: :get do |f| %>
      <%= render 'shared/search' %>
      <% end %>
      <%= render "shared/feed" %>
    </div>
  </div>
<% else %>
...
<% end %>

<script id="user-list-item-template" type="text/x-handlebars-template">
  {{#each micro_posts}}
    <li id="micropost-{{ id }}">
      <a href="/en/users/{{ user.id }}">
        <img alt="{{ user.name }}" class="gravatar" src="{{ user.avatar }}">
      </a>
      <span class="user">
        <a href="/en/users/{{ user.id }}">
          {{ user.name }}
        </a>
      </span>
      <span class="content">
        {{ content }}
      </span>
    </li> 
  {{/each}}
</script> 

<script id="list-comment-template" type="text/x-handlebars-template">
  <div class="form-outline list-cmt-span" style="margin-left: 8%; margin-right: 8%;">
    <span>
      <a class="avatar-cmt" href="#"><img alt="" class="gravatar" src={{comment.user.avatar}}></a>
      <p class="p-comment">{{ comment.text }}</p>
    </span>
  </div>
</script>