config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|ja/ do
    get 'static_pages/home'
    get 'static_pages/help'
    get 'static_pages/contact'
    root 'static_pages#home'
    # resource :static_pages do
    #   collection do
    #     get :index
    #     get :help
    #     get :home
    #   end
    # end
    resources :microposts, only: [:create, :destroy, :index] do
      resources :comments
      resources :likes
    end
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/delete/:id", to: "users#destroy"
    resources :users do
      member do
        get :following, :followers
      end
      collection { post :import }
      collection { get :export }
    end
    resources :relationships, only: [:create, :destroy]
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    get "/logout", to: "sessions#destroy"
    resources :account_activations, only: :edit
    resources :password_resets, only: [:new, :create, :edit, :update] 
    namespace :api, defaults: { format: :json } do
      namespace :v1 do
        post "/login", to: "sessions#create"
        post "/comment", to: "microposts#comment"
        resources :users
        resources :microposts, only: [:index]
      end
    end
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_action :login?, only: [:new, :create, :edit, :update]
  before_action :get_user, only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]

  def new;end

  def edit;end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = t('send_mail.email_reset.')
      redirect_to login_path
    else
      flash.now[:danger] = t('send_mail.email_not_found.')
      render :new
    end
  end

  def update
    if user_params[:password].empty?
      @user.errors.add(:password, t('send_mail.password_empty'))
      render :edit
    elsif @user.update(user_params)
      flash[:info] = t('send_mail.reset_success')
      redirect_to(login_path)
    else
      render :edit
    end
  end

  private

  def get_user
    @user = User.find_by(email: params[:email])
  end

  def valid_user
    return if (@user && @user.activated && @user.authenticated?(:reset, params[:id]))
    redirect_to(root_url)
  end

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def check_expiration
    return unless @user.password_reset_expired?
    flash[:danger] = t('send_mail.email_expired')
    redirect_to(new_password_reset_url)
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, "Reset password") %>
<h1 class="title_form">
    <%= t("form.log_in") %>
Reset password</h1>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
            <%= render 'shared/error_messages' %>
            <%= hidden_field_tag :email, @user.email %>
            <%= f.label t("form.password")%>
            <%= f.password_field :password, class: 'form-control' %>
            <%= f.label t("form.password_confirmation"), "Confirmation" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
            <%= f.submit t("send_mail.update_password"), class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/password_resets/new.html.erb
<% provide :title, "Forgot password" %>
<h1 class="title_form">
    <%= t("home.forgot_password") %>
</h1>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for :password_reset, url: password_resets_url do |f| %>
            <%= f.label "Email" %>
            <%= f.email_field :email, class: "form-control" %>
            <%= f.submit "Submit", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>