config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|ja/ do
    get 'static_pages/home'
    get 'static_pages/help'
    get 'static_pages/contact'
    root 'static_pages#home'
    # resource :static_pages do
    #   collection do
    #     get :index
    #     get :help
    #     get :home
    #   end
    # end
    resources :microposts, only: [:create, :destroy, :index] do
      resources :comments
      resources :likes
    end
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/delete/:id", to: "users#destroy"
    resources :users do
      member do
        get :following, :followers
      end
      collection { post :import }
      collection { get :export }
    end
    resources :relationships, only: [:create, :destroy]
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    get "/logout", to: "sessions#destroy"
    resources :account_activations, only: :edit
    resources :password_resets, only: [:new, :create, :edit, :update] 
    namespace :api, defaults: { format: :json } do
      namespace :v1 do
        post "/login", to: "sessions#create"
        post "/comment", to: "microposts#comment"
        resources :users
        resources :microposts, only: [:index]
      end
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "the_form_contains" %>
      <%= pluralize object.errors.count, "error" %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items, params: { controller: :static_pages, action: :home } %>
<% end %>

app/views/shared/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse css-header">
  <div class="container">
    <%= link_to t("app_name"), root_url, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("header.home"), "/static_pages/home" %></li>
        <li><%= link_to t("header.help"), "/static_pages/help" %></li>
        <li><%= link_to t("header.contact"), "/static_pages/contact" %></li>
        <% if logged_in? %>
          <li><%= link_to t("users"), users_path %></li>
          <li class="dropdown">
            <%= link_to "#", class: "dropdown-toggle", 'data-toggle': "dropdown" do %>
              <%= t "account" %>
              <b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li> <%= link_to "Log out", logout_path %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("header.login"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
  
  <div class="mult-language" id="mult-language">
    <%= link_to image_tag("usa.png", size: "45x23"), locale:"en" %>
    <%= link_to image_tag("ja.png", size: "45x23"), locale:"ja" %>
  </div> 
  <%# <li><%= select_tag(:locale, options_for_select(['English', 'en'], ['Japanese', 'en']])) %>
</header>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class = "mg-bt0" class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <span class="image">
    <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
  </span>
  <input type="button" name="commit" value="Post" class="btn btn-primary btn-post" >
<% end %>

app/views/shared/_search.html.erb
<div class="input-group">
  <input type="text" class="form-control" placeholder="Search" name="search">
  <div class="input-group-btn">
    <button class="btn btn-default" type="submit" >
      <i class="glyphicon glyphicon-search"></i>
    </button>
  </div>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize current_user.microposts.count, "micropost" %></span>