config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|ja/ do
    get 'static_pages/home'
    get 'static_pages/help'
    get 'static_pages/contact'
    root 'static_pages#home'
    # resource :static_pages do
    #   collection do
    #     get :index
    #     get :help
    #     get :home
    #   end
    # end
    resources :microposts, only: [:create, :destroy, :index] do
      resources :comments
      resources :likes
    end
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/delete/:id", to: "users#destroy"
    resources :users do
      member do
        get :following, :followers
      end
      collection { post :import }
      collection { get :export }
    end
    resources :relationships, only: [:create, :destroy]
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    get "/logout", to: "sessions#destroy"
    resources :account_activations, only: :edit
    resources :password_resets, only: [:new, :create, :edit, :update] 
    namespace :api, defaults: { format: :json } do
      namespace :v1 do
        post "/login", to: "sessions#create"
        post "/comment", to: "microposts#comment"
        resources :users
        resources :microposts, only: [:index]
      end
    end
  end
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  scope :newest, -> { order(created_at: :desc) }
  has_one_attached :image
  validates :user_id, presence: true
  validates :content, presence: true, length: {maximum: 140}
  validates :image, content_type: { in: %w[image/jpeg image/gif image/png],
                                  message: "must be a valid image format" },
                                  size: { less_than: 5.megabytes,
                                    message: "should be less than 5MB" }                                

  def display_image
    image.variant resize_to_limit: [500, 200]
  end
end

app/controllers/api/v1/microposts_controller.rb
class Api::V1::MicropostsController < Api::V1::BaseController
  def index
    microposts = Micropost.all.includes(:user, :comments)
    render json: success_message('Successfully',
      ActiveModelSerializers::SerializableResource.new(microposts,
                                                       each_serializer: MicroPostSerializer))
  end

  def comment
    comment = current_user.comments.build(comment_params)
    if comment.save
      render json: success_message('Successfully',
        ActiveModelSerializers::SerializableResource.new(comment,
                                                         each_serializer: CommentSerializer))
    else
      render json: error_message(comment.errors.full_messages.first)
    end
  end

  private

  def comment_params
    { content: params[:content], micropost_id: params[:micropost_id] }
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :correct_user, only: :destroy
  def index;end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = current_user.feed.page(params[:page])
      render "static_pages/home"
    end
  end

  private
  def micropost_params
    params.require(:micropost).permit(:content, :image)
  end

  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    return if @micropost
    flash[:danger] = "Micropost invalid"
    redirect_to request.referrer || root_url
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_form.html.erb
<%= form_with(model: micropost) do |form| %>
  <% if micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>
      <ul>
        <% micropost.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/microposts/_micropost.html.erb
<div class = "css-post">
  <li id="micropost-<%= micropost.id %>">
    <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
    <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
    <span class="content">
      <%= micropost.content %>
      <%= image_tag micropost.display_image if micropost.image.attached? %>
    </span>
    <span class="timestamp">
      Posted <%= time_ago_in_words micropost.created_at %> ago.
      <li class="dropdown">
        <%= link_to "#", class: "dropdown-toggle unsethover", 'data-toggle': "dropdown" do %>
          <p style = "margin: 0"><%= micropost.likes.count %> <%= (micropost.likes.count) == 1 ? 'Like' : 'Likes'%></p>
        <% end %>
        <ul class="dropdown-menu">
          <li style = "width: 350px">
            <% micropost.likes.includes(:user).each do |like| %>
              <%= link_to gravatar_for(like.user, size: 30) %>
              <span class="user"><%= link_to like.user.name %></span>
            <% end %>
          </li>
        </ul>
      </li>
      <div class = "padding_micropost">
        <span class = "icon_like">
          <i class="glyphicon glyphicon-thumbs-up"></i>
          <% pre_like = micropost.likes.find { |like| like.user_id == current_user.id} %>
          <% if pre_like %>
            <%= link_to 'Unlike', micropost_like_path(micropost, pre_like), method: :delete, class: :color_icon%>
          <% else %>
            <%= link_to 'Like', micropost_likes_path(micropost), method: :post %>
          <% end %>
        </span>
        <span class = "comment" id="<%= micropost.id %>">
          <a class = "btn-comment" style = 'cursor:pointer'> comment</a>
        </span>
        <% if current_user? micropost.user %>
          <%= link_to "delete", micropost, method: :delete, data: {confirm: "You sure?"} %>
        <% end %>
        <span class = "btn-showcmt" id="<%= micropost.id %>">
          <a class = "btn-comment" style = 'cursor:pointer'> show more</a>
        </span>
      </div>
    </span>
    <div class="input_comment" style="display: none" id="input_comment-<%= micropost.id %>">
      <%= form_with url: new_micropost_comment_path(micropost), method: :get do |f| %>
      <div class="input-group">
        <input type="text" class="form-control in-comment" placeholder="comment" name="content" style = 'width:690px'  > 
        <div class="input-group-btn">
          <button class="hi" type="submit" hidden>
          </button>
        </div>
      </div>
      <% end %>
    </div>
    <% micropost.comments.each do |comment|%>
      <div class = "hi" style="margin: 0 0 0 60px; display: none;">
        <%= link_to gravatar_for(comment.user, size: 30) %>
        <span class="user"><%= link_to comment.user.name %></span>
        <p >
          <%= comment.content %>
          <% if (current_user? micropost.user) || current_user.id == comment.user.id %>
            <%= link_to "delete", micropost_comment_path(comment.micropost_id,comment.id), method: :delete, data: {confirm: "You sure?"} %>
          <% end %>
        </p>
      </div>
    <% end %>
    <script id="list-comment-template" type="text/x-handlebars-template">
      <div class="form-outline list-cmt-span" style="margin-left: 8%; margin-right: 8%;">
        <span>
          <a class="avatar-cmt" href="#"><img alt="" class="gravatar" src={{comment.avatar}}></a>
          <p class="p-comment">{{ comment.content }}</p>
        </span>
      </div>
    </script>
  </li>
</div>

app/views/microposts/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Microposts</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.title %></td>
        <td><%= micropost.description %></td>
        <td><%= micropost.user_id %></td>
        <td><%= link_to 'Show', micropost %></td>
        <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
        <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<%= javascript_include_tag 'micropost/micropost.js' %>
<h1>New Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @micropost.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @micropost.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @micropost.user_id %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>